name: agro_market
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  responsive_sizer: ^3.3.1
  shared_preferences: ^2.5.3
  auto_route: ^10.1.0+1
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.3  
  build_runner: ^2.5.4           


flutter:
  assets:
    - assets/images/
    - assets/images/onboarding/