import 'package:agro_market/presentation/theme/colors/agro_market_color_palette.dart';
import 'package:agro_market/presentation/theme/colors/agro_market_color_theme_extension.dart';
import 'package:agro_market/presentation/theme/text/agro_market_theme_extension.dart';
import 'package:agro_market/presentation/theme/text/app_fonts.dart';
import 'package:flutter/material.dart';

abstract class AgroMarketTextTheme {
  static AgroMarketThemeExtension get({
    required AgroMarketColorThemeExtension colorTheme,
  }) {
    return AgroMarketThemeExtension(
      appBarTitleBarStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w800,
        color: colorTheme.primary,
        fontSize: 18,
      ),
      profileFollowerStyle: const TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w800,
        color: AgroMarketColorPalette.followerColor,
        fontSize: 12,
      ),
      appBarResultStyleStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.semiBold,
        color: colorTheme.foregroundPrimary,
        fontSize: 18,
      ),
      clickableTextStyle: const TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w500,
        color: AgroMarketColorPalette.midnightGreen10,
        fontSize: 14,
      ),
      requirementInfoTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.medium,
        color: colorTheme.foregroundPrimary,
        fontSize: 14,
      ),
      dialogTitleStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w600,
        color: colorTheme.foregroundPrimary,
        fontSize: 24,
      ),
      dialogBodyStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w400,
        color: colorTheme.foregroundPrimary,
        fontSize: 16,
      ),
      tutorialLabelStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.bold,
        color: colorTheme.foregroundPrimary,
        fontSize: 24,
      ),
      communityIntroTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.bold,
        color: colorTheme.foregroundPrimary,
        fontSize: 24,
      ),
      dialogSubtitleStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w600,
        color: colorTheme.foregroundPrimary,
        fontSize: 16,
      ),
      profileInfoTextStyle: const TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.medium,
        color: AgroMarketColorPalette.secondaryLightColor,
        fontSize: 14,
      ),
      navigationTileTextStyle: const TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w700,
        color: AgroMarketColorPalette.primaryTextLightColor,
        fontSize: 14,
      ),
      retentionBigTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w700,
        color: colorTheme.foregroundPrimary,
        fontSize: 27,
      ),
      settingsTileTitleTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.semiBold,
        color: colorTheme.foregroundPrimary,
        fontSize: 16,
      ),
      resultTimeTextStyle: const TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.semiBold,
        color: AgroMarketColorPalette.primaryTextLightColor,
        fontSize: 12,
      ),
      semiBoldTwelveTextStyle: const TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.semiBold,
        color: AgroMarketColorPalette.secondaryLightColor2,
        fontSize: 12,
      ),
      introTitleTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.semiBold,
        color: colorTheme.foregroundPrimary,
        fontSize: 24,
      ),
      guidedTitleTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.semiBold,
        color: colorTheme.foregroundPrimary,
        fontSize: 26,
      ),
      introBodyTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.medium,
        color: colorTheme.foregroundPrimary,
        fontSize: 14,
      ),
      infoCardAllCapsTextStyle: const TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.medium,
        color: AgroMarketColorPalette.primaryLightColor3,
        fontSize: 14,
        height: 1.5,
      ),
      exerciseDescriptionTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.medium,
        color: colorTheme.foregroundPrimary,
        fontSize: 14,
        height: 1.5,
      ),
      exerciseCardTitleTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.bold,
        color: colorTheme.foregroundPrimary,
        fontSize: 16,
      ),
      exerciseBlockTitleTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.semiBold,
        color: colorTheme.foregroundPrimary,
        fontSize: 16,
      ),
      meditationTitleTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.semiBold,
        color: colorTheme.foregroundPrimary,
        fontSize: 14,
      ),
      meditationSubtitleTextStyle: const TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.semiBold,
        color: AgroMarketColorPalette.accentLightColor2,
        fontSize: 10,
      ),
      unselectedSegmentTitleTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.regular,
        color: colorTheme.tertiary,
        fontSize: 14,
      ),
      selectedSegmentTitleTextStyle: const TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.regular,
        color: AgroMarketColorPalette.white,
        fontSize: 14,
      ),
      roundTextStyle: const TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.regular,
        color: AgroMarketColorPalette.secondaryLightColor,
        fontSize: 14,
      ),
      stepTextStyle: const TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.regular,
        color: AgroMarketColorPalette.lightGrey2,
        fontSize: 18,
      ),
      greyTextStyle: const TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.regular,
        color: AgroMarketColorPalette.lightGrey2,
        fontSize: 12,
      ),
      ratioBarTextStyle: const TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.regular,
        color: AgroMarketColorPalette.white,
        fontSize: 12,
      ),
      ratioTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.regular,
        color: colorTheme.foregroundPrimary,
        fontSize: 12,
      ),
      tileTitleTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.semiBold,
        color: colorTheme.foregroundPrimary,
        fontSize: 14,
      ),
      paragraphTitleTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w600,
        fontSize: 16,
        color: colorTheme.foregroundPrimary,
      ),
      paragraphSubtitleTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w400,
        fontSize: 14,
        color: colorTheme.foregroundPrimary,
      ),
      textInputTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.medium,
        fontSize: 16,
        color: colorTheme.foregroundPrimary,
      ),
      bulletTitleTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w600,
        fontSize: 16,
        color: colorTheme.foregroundPrimary,
      ),
      bulletSubtitleTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w600,
        fontSize: 14,
        color: colorTheme.foregroundPrimary,
      ),
      totalTimeTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.regular,
        fontSize: 12,
        color: colorTheme.tertiary,
      ),
      hexagonNavigationTileTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.semiBold,
        color: colorTheme.foregroundPrimary,
        fontSize: 16,
      ),
      reminderCountTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.bold,
        color: colorTheme.foregroundPrimary,
        fontSize: 16,
      ),
      reminderTimesTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w400,
        color: colorTheme.secondary,
        fontSize: 14,
      ),
      introPageTitle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.bold,
        color: colorTheme.foregroundPrimary,
        fontSize: 24,
      ),
      blueGreyStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w400,
        color: colorTheme.foregroundPrimary,
        fontSize: 16,
      ),
      introPageDescription: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w300,
        color: colorTheme.foregroundPrimary,
        fontSize: 14,
      ),
      hexTitleStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w700,
        color: colorTheme.foregroundPrimary,
        fontSize: 18,
      ),
      hexSubtitleStyle: const TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w500,
        color: AgroMarketColorPalette.primaryTextLightColor,
        fontSize: 13,
      ),
      showerTimerText: TextStyle(
        color: colorTheme.foregroundPrimary,
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.semiBold,
        fontSize: 40,
      ),
      communityTitleStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.bold,
        color: colorTheme.foregroundPrimary,
        fontSize: 22,
      ),
      appBarActionTextStyle: const TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w500,
        color: AgroMarketColorPalette.accentLightColor,
        fontSize: 16,
      ),
      retentionTimerTimeText: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.bold,
        color: colorTheme.primary,
        fontSize: 18,
      ),
      badgeUnEarnedLabelTextStyle: const TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w400,
        color: AgroMarketColorPalette.primaryLightColor3,
        fontSize: 12,
      ),
      beginnersGuideListItemStatusTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.semiBold,
        fontSize: 12,
        color: colorTheme.foregroundPrimary,
      ),
      chartLabelsStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w500,
        color: colorTheme.foregroundPrimary,
        fontSize: 12,
      ),
      dateTimePickerHeaderStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.semiBold,
        fontSize: 14.45,
        color: colorTheme.foregroundPrimary,
      ),
      streakTitleStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w600,
        color: colorTheme.primary,
        fontSize: 20,
      ),
      dateTimeDayNameStyle: TextStyle(
        color: colorTheme.foregroundPrimary,
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.regular,
        fontSize: 13.63,
      ),
      dateTimeDayCellStyle: TextStyle(
        color: colorTheme.foregroundPrimary,
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: AppFonts.semiBold,
        fontSize: 10,
      ),
      subTitleTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w400,
        color: colorTheme.foregroundPrimary,
        fontSize: 14,
      ),
      eLearningLessonTitleTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.bold,
        color: colorTheme.foregroundPrimary,
        fontSize: 18,
      ),
      eLearningLessonDescriptionTextStyle: const TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w400,
        color: AgroMarketColorPalette.secondaryDarkColor,
        fontSize: 14,
      ),
      eLearningLessonsTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w500,
        color: colorTheme.foregroundPrimary,
        fontSize: 16,
      ),
      redeemBadgeTitleTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w700,
        color: colorTheme.foregroundPrimary,
        fontSize: 20,
      ),
      tapInfoTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w300,
        color: colorTheme.foregroundPrimary,
        fontSize: 14,
      ),
      badgeDialogRarityInfoTextStyle: const TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w500,
        color: AgroMarketColorPalette.secondaryLightColor2,
        fontSize: 14,
      ),
      longestRoundTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w600,
        fontSize: 14,
        color: colorTheme.foregroundPrimary,
      ),
      averageRoundTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w600,
        fontSize: 14,
        color: colorTheme.foregroundPrimary,
      ),
      thankYouForFeedbackTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w600,
        color: colorTheme.foregroundPrimary,
        fontSize: 18,
      ),
      thankYouForFeedbackSubtitleTextStyle: TextStyle(
        fontFamily: AppFonts.outfitFontFamily,
        fontWeight: FontWeight.w300,
        color: colorTheme.foregroundPrimary,
        fontSize: 14,
      ),
    );
  }
}
